export default [
  {
    name: 'candy cane',
    multiple: 5,
    colorList: [
      { color: '#FF0000', leadingEdge: true, position: 0 },
      {
        color: '#FFFFFF',
        leadingEdge: true,
        position: 50,
      },
    ],
  },
  {
    name: 'green wave',
    multiple: 3,
    colorList: [
      { color: '#00ff00', leadingEdge: true, position: 0 },
      { color: '#006400', leadingEdge: true, position: 30 },
      { color: '#003200', leadingEdge: true, position: 42 },
      { color: '#000000', leadingEdge: true, position: 50 },
    ],
  },
  {
    name: 'cyan wave',
    multiple: 3,
    colorList: [
      { color: '#00ffff', leadingEdge: true, position: 0 },
      { color: '#006464', leadingEdge: true, position: 30 },
      { color: '#003232', leadingEdge: true, position: 42 },
      { color: '#000000', leadingEdge: true, position: 50 },
    ],
  },
  {
    name: 'fireballs',
    multiple: 1,
    colorList: [
      { color: '#f7ac16', leadingEdge: true, position: 0 },
      { color: '#fcea48', leadingEdge: true, position: 1 },
      { color: '#d00101', leadingEdge: true, position: 5 },
      { color: '#640101', leadingEdge: true, position: 20 },
      { color: '#000000', leadingEdge: true, position: 30 },
      { color: '#00faff', leadingEdge: true, position: 50 },
      { color: '#6bfbff', leadingEdge: true, position: 51 },
      { color: '#00faff', leadingEdge: true, position: 54 },
      { color: '#0cc5c8', leadingEdge: true, position: 60 },
      { color: '#0d7376', leadingEdge: true, position: 70 },
      { color: '#000000', leadingEdge: true, position: 80 },
    ],
  },
  {
    name: 'rainbow',
    multiple: 1,
    colorList: [
      { color: '#ff0004', leadingEdge: true, position: 0 },
      { color: '#ffff01', leadingEdge: true, position: 16 },
      { color: '#00ff00', leadingEdge: true, position: 33 },
      { color: '#01ffff', leadingEdge: true, position: 50 },
      { color: '#0101ff', leadingEdge: true, position: 66 },
      { color: '#ff01ff', leadingEdge: true, position: 83 },
    ],
  },
  {
    name: 'rainbow flag',
    multiple: 1,
    colorList: [
      { color: '#ff0004', leadingEdge: true, position: 0 },
      { color: '#ff8001', leadingEdge: true, position: 16 },
      { color: '#ffff00', leadingEdge: true, position: 33 },
      { color: '#01ff01', leadingEdge: true, position: 50 },
      { color: '#0101ff', leadingEdge: true, position: 66 },
      { color: '#9701ff', leadingEdge: true, position: 83 },
    ],
  },
  {
    name: 'rainbow flag split',
    multiple: 1,
    colorList: [
      { color: '#ff0004', leadingEdge: true, position: 0 },
      { color: '#000000', position: 12, leadingEdge: true },
      { color: '#ff8001', leadingEdge: true, position: 16 },
      { color: '#000000', position: 29, leadingEdge: true },
      { color: '#ffff00', leadingEdge: true, position: 33 },
      { color: '#000000', position: 46, leadingEdge: true },
      { color: '#01ff01', leadingEdge: true, position: 50 },
      { color: '#000000', position: 62, leadingEdge: true },
      { color: '#0101ff', leadingEdge: true, position: 66 },
      { color: '#000000', position: 79, leadingEdge: true },
      { color: '#9701ff', leadingEdge: true, position: 83 },
      { color: '#000000', position: 96, leadingEdge: true },
    ],
  },
  {
    name: 'trans flag',
    multiple: 2,
    gap: 20,
    colorList: [
      { color: '#4cf5f9', position: 0, leadingEdge: true },
      { color: '#f098ac', position: 20, leadingEdge: true },
      { color: '#ffffff', position: 40, leadingEdge: true },
      { color: '#f098ac', position: 60, leadingEdge: true },
      { color: '#4cf5f9', position: 80, leadingEdge: true },
    ],
  },
  {
    name: 'green vs magenta',
    multiple: 1,
    colorList: [
      { color: '#00ff00', leadingEdge: true, position: 0 },
      { color: '#000000', leadingEdge: true, position: 10 },
      { color: '#00ff00', leadingEdge: true, position: 13 },
      { color: '#000000', leadingEdge: true, position: 21 },
      { color: '#00ff00', leadingEdge: true, position: 24 },
      { color: '#000000', leadingEdge: true, position: 28 },
      { color: '#ff01ff', leadingEdge: true, position: 50 },
      { color: '#000000', leadingEdge: true, position: 60 },
      { color: '#ff01ff', leadingEdge: true, position: 63 },
      { color: '#000000', leadingEdge: true, position: 71 },
      { color: '#ff01ff', leadingEdge: true, position: 74 },
      { color: '#000000', leadingEdge: true, position: 78 },
    ],
  },
  {
    name: 'green & magenta fireballs',
    multiple: 1,
    colorList: [
      { color: '#ff00ff', leadingEdge: true, position: 0 },
      { color: '#ffbbff', position: 1, leadingEdge: true },
      { color: '#fa79fa', position: 4, leadingEdge: true },
      { color: '#ff00ff', position: 7, leadingEdge: false },
      { color: '#bd00bd', position: 10, leadingEdge: false },
      { color: '#6e006e', position: 20, leadingEdge: true },
      { color: '#000000', leadingEdge: true, position: 30 },
      { color: '#00ff00', leadingEdge: true, position: 50 },
      { color: '#d2ffe4', position: 51, leadingEdge: false },
      { color: '#45ff8b', position: 54, leadingEdge: true },
      { color: '#00ff00', position: 57, leadingEdge: false },
      { color: '#0b9b0b', position: 60, leadingEdge: false },
      { color: '#0c5f0c', leadingEdge: true, position: 70 },
      { color: '#000000', leadingEdge: true, position: 80 },
    ],
  },

  {
    name: 'blue & yellow fireballs',
    multiple: 1,
    colorList: [
      { color: '#0000ff', position: 0, leadingEdge: true },
      { color: '#cacaff', position: 1, leadingEdge: true },
      { color: '#7979fa', position: 4, leadingEdge: true },
      { color: '#0000ff', position: 7, leadingEdge: false },
      { color: '#0000bd', position: 10, leadingEdge: false },
      { color: '#00006e', position: 20, leadingEdge: true },
      { color: '#000000', leadingEdge: true, position: 30 },
      { color: '#ffff00', position: 50, leadingEdge: true },
      { color: '#ffffd2', position: 51, leadingEdge: false },
      { color: '#ffff45', position: 54, leadingEdge: true },
      { color: '#ffff00', position: 57, leadingEdge: false },
      { color: '#9b9b0b', position: 60, leadingEdge: false },
      { color: '#5f5f0c', position: 70, leadingEdge: true },
      { color: '#000000', leadingEdge: true, position: 80 },
    ],
  },
  {
    name: 'disney plus',
    multiple: 1,
    gap: 10,
    colorList: [
      {
        color: '#ffffff',
        leadingEdge: true,
        position: 0,
      },
      {
        color: '#c4f9fa',
        position: 6,
        leadingEdge: true,
      },
      {
        color: '#30f8fa',
        position: 14,
        leadingEdge: false,
      },
      {
        color: '#1172c9',
        position: 28,
        leadingEdge: false,
      },
      {
        color: '#0847ab',
        position: 40,
        leadingEdge: false,
      },
      {
        color: '#0b1152',
        position: 60,
        leadingEdge: false,
      },
      {
        color: '#000000',
        position: 100,
        leadingEdge: false,
      },
    ],
  },
  {
    name: 'smiley face',
    multiple: 1,
    colorList: [
      { color: '#000000', position: 0, leadingEdge: true },
      { color: '#ffff00', position: 5, leadingEdge: true },
      { color: '#000000', position: 45, leadingEdge: true },
      { color: '#ffff00', position: 62, leadingEdge: true },
      { color: '#000000', position: 68, leadingEdge: true },
      { color: '#ffff00', position: 82, leadingEdge: true },
      { color: '#000000', position: 88, leadingEdge: true },
    ],
  },
  {
    name: 'CMY chase',
    multiple: 1,
    colorList: [
      { color: '#00ffff', leadingEdge: true, position: 0 },
      { color: '#006464', position: 10, leadingEdge: false },
      { color: '#003232', position: 14, leadingEdge: false },
      { color: '#000000', position: 32, leadingEdge: true },
      { color: '#ff00ff', position: 33, leadingEdge: true },
      { color: '#640064', position: 43, leadingEdge: false },
      { color: '#320032', position: 47, leadingEdge: false },
      { color: '#000000', position: 66, leadingEdge: true },
      { color: '#ffff00', position: 67, leadingEdge: true },
      { color: '#646400', position: 76, leadingEdge: false },
      { color: '#323200', position: 80, leadingEdge: false },
      { color: '#000000', position: 100, leadingEdge: true },
    ],
  },
  {
    name: 'RGB chase',
    multiple: 1,
    colorList: [
      { color: '#0000ff', position: 0, leadingEdge: true },
      { color: '#000064', position: 10, leadingEdge: false },
      { color: '#000032', position: 14, leadingEdge: false },
      { color: '#000000', position: 32, leadingEdge: true },
      { color: '#ff0000', position: 33, leadingEdge: true },
      { color: '#640000', position: 43, leadingEdge: false },
      { color: '#320000', position: 47, leadingEdge: false },
      { color: '#000000', position: 66, leadingEdge: true },
      { color: '#00ff00', position: 67, leadingEdge: true },
      { color: '#006400', position: 76, leadingEdge: false },
      { color: '#003200', position: 80, leadingEdge: false },
      { color: '#000000', position: 100, leadingEdge: true },
    ],
  },
  {
    name: 'RGB wave',
    multiple: 1,
    colorList: [
      { color: '#0000ff', position: 0, leadingEdge: true },
      { color: '#000064', position: 10, leadingEdge: true },
      { color: '#000032', position: 14, leadingEdge: true },
      { color: '#000000', position: 16, leadingEdge: true },
      { color: '#ff0000', position: 33, leadingEdge: true },
      { color: '#640000', position: 43, leadingEdge: true },
      { color: '#320000', position: 47, leadingEdge: true },
      { color: '#000000', position: 50, leadingEdge: true },
      { color: '#00ff00', position: 67, leadingEdge: true },
      { color: '#006400', position: 76, leadingEdge: true },
      { color: '#003200', position: 80, leadingEdge: true },
      { color: '#000000', position: 84, leadingEdge: true },
    ],
  },
  {
    name: 'picnic',
    multiple: '5',
    gap: 0,
    colorList: [
      {
        color: '#aed37a',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#f1f0a0',
        position: 35,
        leadingEdge: true,
      },
      {
        color: '#fede86',
        position: 50,
        leadingEdge: true,
      },
      {
        color: '#f1f0a0',
        position: 85,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'paranoia',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#68cfa9',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#c1cdaf',
        position: 17,
        leadingEdge: true,
      },
      {
        color: '#cdb69b',
        position: 22,
        leadingEdge: true,
      },
      {
        color: '#ea9e9b',
        position: 25,
        leadingEdge: true,
      },
      {
        color: '#e66b7e',
        position: 30,
        leadingEdge: true,
      },
      {
        color: '#ea9e9b',
        position: 70,
        leadingEdge: true,
      },
      {
        color: '#cdb69b',
        position: 75,
        leadingEdge: true,
      },
      {
        color: '#c1cdaf',
        position: 78,
        leadingEdge: true,
      },
      {
        color: '#68cfa9',
        position: 83,
        leadingEdge: true,
      },
    ],
  },

  {
    name: 'shirt - rear hub',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#c34545',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#a0a0a0',
        position: 14,
        leadingEdge: true,
      },
      {
        color: '#c7d21d',
        position: 50,
        leadingEdge: true,
      },
      {
        color: '#4c7488',
        position: 73,
        leadingEdge: true,
      },
      {
        color: '#4abaf8',
        position: 77,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'shirt - front tire',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#c34545',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#a0a0a0',
        position: 20,
        leadingEdge: true,
      },
      {
        color: '#c7d21d',
        position: 20,
        leadingEdge: true,
      },
      {
        color: '#c34545',
        position: 36,
        leadingEdge: true,
      },
      {
        color: '#4abaf8',
        position: 50,
        leadingEdge: true,
      },
      {
        color: '#4c7488',
        position: 65,
        leadingEdge: true,
      },
      {
        color: '#000000',
        position: 80,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'shirt - front hub',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#c7d21d',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#1e3f52',
        position: 52,
        leadingEdge: true,
      },
      {
        color: '#fc8121',
        position: 68,
        leadingEdge: true,
      },
      {
        color: '#a0a0a0',
        position: 80,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'shirt - front chainring',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#c34545',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#4abaf8',
        position: 65,
        leadingEdge: true,
      },
      {
        color: '#fc8121',
        position: 90,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'shirt - handlebars big',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#c7d21d',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#4abaf8',
        position: 50,
        leadingEdge: true,
      },
      {
        color: '#c7d21d',
        position: 58,
        leadingEdge: true,
      },
      {
        color: '#c34545',
        position: 75,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'shirt - handlebars small',
    multiple: '1',
    gap: 0,
    colorList: [
      {
        color: '#c34545',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#4abaf8',
        position: 73,
        leadingEdge: true,
      },
      {
        color: '#fc8121',
        position: 80,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'flag - italy mexico',
    multiple: '3',
    gap: 30,
    colorList: [
      {
        color: '#0d6c04',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#ffffff',
        position: 33,
        leadingEdge: true,
      },
      {
        color: '#f20007',
        position: 67,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'flag - ireland india',
    multiple: '3',
    gap: 30,
    colorList: [
      {
        color: '#1b8d50',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#ffffff',
        position: 33,
        leadingEdge: true,
      },
      {
        color: '#fc7330',
        position: 67,
        leadingEdge: true,
      },
    ],
  },
  {
    name: 'flag - netherlands france',
    multiple: '3',
    gap: 30,
    colorList: [
      {
        color: '#ff0000',
        position: 0,
        leadingEdge: true,
      },
      {
        color: '#ffffff',
        position: 33,
        leadingEdge: true,
      },
      {
        color: '#0000ff',
        position: 67,
        leadingEdge: true,
      },
    ],
  },
]
