export default [
    {
        name: 'candy cane',
        multiple: 5,
        colorList: [
            {
                color: '#FF0000',
                leadingEdge: true,
                position: 0,
            },
            {
                color: '#FFFFFF',
                leadingEdge: true,
                position: 50,
            },
        ],
    },
    {
        name: 'green wave',
        multiple: 3,
        colorList: [
            { color: '#00ff00', leadingEdge: true, position: 0 },
            { color: '#006400', leadingEdge: true, position: 30 },
            { color: '#003200', leadingEdge: true, position: 42 },
            { color: '#000000', leadingEdge: true, position: 50 },
        ],
    },
    {
        name: 'cyan wave',
        multiple: 3,
        colorList: [
            { color: '#00ffff', leadingEdge: true, position: 0 },
            { color: '#006464', leadingEdge: true, position: 30 },
            { color: '#003232', leadingEdge: true, position: 42 },
            { color: '#000000', leadingEdge: true, position: 50 },
        ],
    },
    {
        name: 'fireballs',
        multiple: 1,
        colorList: [
            { color: '#f7ac16', leadingEdge: true, position: 0 },
            { color: '#fcea48', leadingEdge: true, position: 1 },
            { color: '#d00101', leadingEdge: true, position: 5 },
            { color: '#640101', leadingEdge: true, position: 20 },
            { color: '#000000', leadingEdge: true, position: 30 },
            { color: '#00faff', leadingEdge: true, position: 50 },
            { color: '#6bfbff', leadingEdge: true, position: 51 },
            { color: '#00faff', leadingEdge: true, position: 54 },
            { color: '#0cc5c8', leadingEdge: true, position: 60 },
            { color: '#0d7376', leadingEdge: true, position: 70 },
            { color: '#000000', leadingEdge: true, position: 80 },
        ],
    },
    {
        name: 'rainbow',
        multiple: 1,
        colorList: [
            { color: '#ff0004', leadingEdge: true, position: 0 },
            { color: '#ffff01', leadingEdge: true, position: 16 },
            { color: '#00ff00', leadingEdge: true, position: 33 },
            { color: '#01ffff', leadingEdge: true, position: 50 },
            { color: '#0101ff', leadingEdge: true, position: 66 },
            { color: '#ff01ff', leadingEdge: true, position: 83 },
        ],
    },
    {
        name: 'rainbow flag',
        multiple: 1,
        colorList: [
            { color: '#ff0004', leadingEdge: true, position: 0 },
            { color: '#ff8001', leadingEdge: true, position: 16 },
            { color: '#ffff00', leadingEdge: true, position: 33 },
            { color: '#01ff01', leadingEdge: true, position: 50 },
            { color: '#0101ff', leadingEdge: true, position: 66 },
            { color: '#9701ff', leadingEdge: true, position: 83 },
        ],
    },
    {
        name: 'rainbow flag split',
        multiple: 1,
        colorList: [
            {color: "#ff0004", leadingEdge: true, position: 0},
            {color: "#000000", position: 12, leadingEdge: true},
            {color: "#ff8001", leadingEdge: true, position: 16},
            {color: "#000000", position: 29, leadingEdge: true},
            {color: "#ffff00", leadingEdge: true, position: 33},
            {color: "#000000", position: 46, leadingEdge: true},
            {color: "#01ff01", leadingEdge: true, position: 50},
            {color: "#000000", position: 62, leadingEdge: true},
            {color: "#0101ff", leadingEdge: true, position: 66},
            {color: "#000000", position: 79, leadingEdge: true},
            {color: "#9701ff", leadingEdge: true, position: 83},
            {color: "#000000", position: 96, leadingEdge: true}
        ],
    },
    {
        name: 'trans flag',
        multiple: 2,
        colorList: [
            {color: "#4cf5f9", position: 0, leadingEdge: true},
            {color: "#f098ac", position: 20, leadingEdge: true},
            {color: "#ffffff", position: 40, leadingEdge: true},
            {color: "#f098ac", position: 60, leadingEdge: true},
            {color: "#4cf5f9", position: 80, leadingEdge: true}
        ],
    },
    {
        name: 'green vs magenta',
        multiple: 1,
        colorList: [
            { color: '#00ff00', leadingEdge: true, position: 0 },
            { color: '#000000', leadingEdge: true, position: 10 },
            { color: '#00ff00', leadingEdge: true, position: 13 },
            { color: '#000000', leadingEdge: true, position: 21 },
            { color: '#00ff00', leadingEdge: true, position: 24 },
            { color: '#000000', leadingEdge: true, position: 28 },
            { color: '#ff01ff', leadingEdge: true, position: 50 },
            { color: '#000000', leadingEdge: true, position: 60 },
            { color: '#ff01ff', leadingEdge: true, position: 63 },
            { color: '#000000', leadingEdge: true, position: 71 },
            { color: '#ff01ff', leadingEdge: true, position: 74 },
            { color: '#000000', leadingEdge: true, position: 78 },
        ],
    },
    {
        name: 'green & magenta fireballs',
        multiple: 1,
        colorList: [
            { color: '#ff00ff', leadingEdge: true, position: 0 },
            { color: '#ffbbff', position: 1, leadingEdge: true },
            { color: '#fa79fa', position: 4, leadingEdge: true },
            { color: '#ff00ff', position: 7, leadingEdge: false },
            { color: '#bd00bd', position: 10, leadingEdge: false },
            { color: '#6e006e', position: 20, leadingEdge: true },
            { color: '#000000', leadingEdge: true, position: 30 },
            { color: '#00ff00', leadingEdge: true, position: 50 },
            { color: '#d2ffe4', position: 51, leadingEdge: false },
            { color: '#45ff8b', position: 54, leadingEdge: true },
            { color: '#00ff00', position: 57, leadingEdge: false },
            { color: '#0b9b0b', position: 60, leadingEdge: false },
            { color: '#0c5f0c', leadingEdge: true, position: 70 },
            { color: '#000000', leadingEdge: true, position: 80 },
        ],
    },

    {
        name: 'blue & yellow fireballs',
        multiple: 1,
        colorList: [
            {color: "#0000ff", position: 0, leadingEdge: true},
            {color: "#cacaff", position: 1, leadingEdge: true},
            {color: "#7979fa", position: 4, leadingEdge: true},
            {color: "#0000ff", position: 7, leadingEdge: false},
            {color: "#0000bd", position: 10, leadingEdge: false},
            {color: "#00006e", position: 20, leadingEdge: true},
            {color: "#000000", leadingEdge: true, position: 30},
            {color: "#ffff00", position: 50, leadingEdge: true},
            {color: "#ffffd2", position: 51, leadingEdge: false},
            {color: "#ffff45", position: 54, leadingEdge: true},
            {color: "#ffff00", position: 57, leadingEdge: false},
            {color: "#9b9b0b", position: 60, leadingEdge: false},
            {color: "#5f5f0c", position: 70, leadingEdge: true},
            {color: "#000000", leadingEdge: true, position: 80}
        ],
    },
    {
        name: 'disney plus',
        multiple: 1,
        colorList: [
            { color: '#ffffff', leadingEdge: true, position: 0 },
            { color: '#c4f9fa', leadingEdge: true, position: 3 },
            { color: '#30f8fa', leadingEdge: false, position: 7 },
            { color: '#1172c9', leadingEdge: false, position: 14 },
            { color: '#0847ab', leadingEdge: false, position: 20 },
            { color: '#0b1152', leadingEdge: false, position: 30 },
            { color: '#000000', leadingEdge: false, position: 70 },
        ],
    },
    {
        name: 'smiley face',
        multiple: 1,
        colorList: [
            { color: '#000000', position: 0, leadingEdge: true },
            { color: '#ffff00', position: 5, leadingEdge: true },
            { color: '#000000', position: 45, leadingEdge: true },
            { color: '#ffff00', position: 62, leadingEdge: true },
            { color: '#000000', position: 68, leadingEdge: true },
            { color: '#ffff00', position: 82, leadingEdge: true },
            { color: '#000000', position: 88, leadingEdge: true },
        ],
    },
    {
        name: 'CMY chase',
        multiple: 1,
        colorList: [
            {color: "#00ffff", leadingEdge: true, position: 0},
            {color: "#006464", position: 10, leadingEdge: false},
            {color: "#003232", position: 14, leadingEdge: false},
            {color: "#000000", position: 32, leadingEdge: true},
            {color: "#ff00ff", position: 33, leadingEdge: true},
            {color: "#640064", position: 43, leadingEdge: false},
            {color: "#320032", position: 47, leadingEdge: false},
            {color: "#000000", position: 66, leadingEdge: true},
            {color: "#ffff00", position: 67, leadingEdge: true},
            {color: "#646400", position: 76, leadingEdge: false},
            {color: "#323200", position: 80, leadingEdge: false},
            {color: "#000000", position: 100, leadingEdge: true}
        ],
    },
    {
        name: 'RGB chase',
        multiple: 1,
        colorList: [
        
            {color: "#0000ff", position: 0, leadingEdge: true},
            {color: "#000064", position: 10, leadingEdge: false},
            {color: "#000032", position: 14, leadingEdge: false},
            {color: "#000000", position: 32, leadingEdge: true},
            {color: "#ff0000", position: 33, leadingEdge: true},
            {color: "#640000", position: 43, leadingEdge: false},
            {color: "#320000", position: 47, leadingEdge: false},
            {color: "#000000", position: 66, leadingEdge: true},
            {color: "#00ff00", position: 67, leadingEdge: true},
            {color: "#006400", position: 76, leadingEdge: false},
            {color: "#003200", position: 80, leadingEdge: false},
            {color: "#000000", position: 100, leadingEdge: true}
        ],
    },
    {
        name: 'RGB wave',
        multiple: 1,
        colorList: [
            {color: "#0000ff", position: 0, leadingEdge: true},
            {color: "#000064", position: 10, leadingEdge: true},
            {color: "#000032", position: 14, leadingEdge: true},
            {color: "#000000", position: 16, leadingEdge: true},
            {color: "#ff0000", position: 33, leadingEdge: true},
            {color: "#640000", position: 43, leadingEdge: true},
            {color: "#320000", position: 47, leadingEdge: true},
            {color: "#000000", position: 50, leadingEdge: true},
            {color: "#00ff00", position: 67, leadingEdge: true},
            {color: "#006400", position: 76, leadingEdge: true},
            {color: "#003200", position: 80, leadingEdge: true},
            {color: "#000000", position: 84, leadingEdge: true}
        ],
    },

]


