export default [
    {
        name: 'candy cane',
        multiple: 5,
        colorList: [
            {
                color: '#FF0000',
                leadingEdge: true,
                position: 0,
            },
            {
                color: '#FFFFFF',
                leadingEdge: true,
                position: 50,
            },
        ],
    },
    {
        name: 'green wave',
        multiple: 3,
        colorList: [
            { color: '#00ff00', leadingEdge: true, position: 0 },
            { color: '#006400', leadingEdge: true, position: 30 },
            { color: '#003200', leadingEdge: true, position: 42 },
            { color: '#000000', leadingEdge: true, position: 50 },
        ],
    },
    {
        name: 'fireballs',
        multiple: 1,
        colorList: [
            { color: '#f7ac16', leadingEdge: true, position: 0 },
            { color: '#fcea48', leadingEdge: true, position: 1 },
            { color: '#d00101', leadingEdge: true, position: 5 },
            { color: '#640101', leadingEdge: true, position: 20 },
            { color: '#000000', leadingEdge: true, position: 30 },
            { color: '#00faff', leadingEdge: true, position: 50 },
            { color: '#6bfbff', leadingEdge: true, position: 51 },
            { color: '#00faff', leadingEdge: true, position: 54 },
            { color: '#0cc5c8', leadingEdge: true, position: 60 },
            { color: '#0d7376', leadingEdge: true, position: 70 },
            { color: '#000000', leadingEdge: true, position: 80 },
        ],
    },
    {
        name: 'rainbow',
        multiple: 1,
        colorList: [
            { color: '#ff0004', leadingEdge: true, position: 0 },
            { color: '#ffff01', leadingEdge: true, position: 16 },
            { color: '#00ff00', leadingEdge: true, position: 33 },
            { color: '#01ffff', leadingEdge: true, position: 50 },
            { color: '#0101ff', leadingEdge: true, position: 66 },
            { color: '#ff01ff', leadingEdge: true, position: 83 },
        ],
    },
    {
        name: 'rainbow flag',
        multiple: 1,
        colorList: [
            { color: '#ff0004', leadingEdge: true, position: 0 },
            { color: '#ff8001', leadingEdge: true, position: 16 },
            { color: '#ffff00', leadingEdge: true, position: 33 },
            { color: '#01ff01', leadingEdge: true, position: 50 },
            { color: '#0101ff', leadingEdge: true, position: 66 },
            { color: '#9701ff', leadingEdge: true, position: 83 },
        ],
    },
    {
        name: 'green vs magenta',
        multiple: 1,
        colorList: [
            { color: '#00ff00', leadingEdge: true, position: 0 },
            { color: '#000000', leadingEdge: true, position: 10 },
            { color: '#00ff00', leadingEdge: true, position: 13 },
            { color: '#000000', leadingEdge: true, position: 21 },
            { color: '#00ff00', leadingEdge: true, position: 24 },
            { color: '#000000', leadingEdge: true, position: 28 },
            { color: '#ff01ff', leadingEdge: true, position: 50 },
            { color: '#000000', leadingEdge: true, position: 60 },
            { color: '#ff01ff', leadingEdge: true, position: 63 },
            { color: '#000000', leadingEdge: true, position: 71 },
            { color: '#ff01ff', leadingEdge: true, position: 74 },
            { color: '#000000', leadingEdge: true, position: 78 },
        ],
    },
    {
        name: 'green & magenta fireballs',
        multiple: 1,
        colorList: [
            { color: '#ff00ff', leadingEdge: true, position: 0 },
            { color: '#ffbbff', position: 1, leadingEdge: true },
            { color: '#fa79fa', position: 4, leadingEdge: true },
            { color: '#ff00ff', position: 7, leadingEdge: false },
            { color: '#bd00bd', position: 10, leadingEdge: false },
            { color: '#6e006e', position: 20, leadingEdge: true },
            { color: '#000000', leadingEdge: true, position: 30 },
            { color: '#00ff00', leadingEdge: true, position: 50 },
            { color: '#d2ffe4', position: 51, leadingEdge: false },
            { color: '#45ff8b', position: 54, leadingEdge: true },
            { color: '#00ff00', position: 57, leadingEdge: false },
            { color: '#0b9b0b', position: 60, leadingEdge: false },
            { color: '#0c5f0c', leadingEdge: true, position: 70 },
            { color: '#000000', leadingEdge: true, position: 80 },
        ],
    },
    {
        name: 'disney plus',
        multiple: 1,
        colorList: [
            { color: '#ffffff', leadingEdge: true, position: 0 },
            { color: '#c4f9fa', leadingEdge: true, position: 3 },
            { color: '#30f8fa', leadingEdge: false, position: 7 },
            { color: '#1172c9', leadingEdge: false, position: 14 },
            { color: '#0847ab', leadingEdge: false, position: 20 },
            { color: '#0b1152', leadingEdge: false, position: 30 },
            { color: '#000000', leadingEdge: false, position: 70 },
        ],
    },
    {
        name: 'smiley face',
        multiple: 1,
        colorList: [
            { color: '#000000', position: 0, leadingEdge: true },
            { color: '#ffff00', position: 5, leadingEdge: true },
            { color: '#000000', position: 45, leadingEdge: true },
            { color: '#ffff00', position: 62, leadingEdge: true },
            { color: '#000000', position: 68, leadingEdge: true },
            { color: '#ffff00', position: 82, leadingEdge: true },
            { color: '#000000', position: 88, leadingEdge: true },
        ],
    },
]
